### ISSUE TITLE
Symfony 4 + Private services by default

### ISSUE THREAD

**Issue by ruudk** [resquebundle/resque#39] opened 2018-08-10 07:04 UTC
I heard there are plans to make this library compatible with Symfony 4. One big issue is that services become private by default. That means that you cannot query them from the Container anymore. 

Instead of telling users to make the services public, I think it would be good to find a solution within this bundle.

Currently, the Job is responsible for creating itself, the arguments, and the execution. In a very nasty way ($job->args) etc. What if we split this up in a Job and a JobHandler? That way, a JobHandler can be a Symfony service that is responsible for executing a given Job. The Job only contains the payload.

This would be a BC break of course. 

WDYT?

**Comment by PhilETaylor** [comment] 2018-08-10 11:09
Duplicate of #37

**Closed as completed by PhilETaylor** 2018-08-10 11:09 UTC
