### ISSUE TITLE
worker getting stalled after running one task

### ISSUE THREAD

**Issue by vamsiikrishna** [resquebundle/resque#24] opened 2017-07-24 15:05 UTC
Hi .
I am having this issue where the background worker is getting stalled after competing the first job in a Queue.

Example:
```
...................................................................................
...................................................................................
...................................................................................
[info] [19:56:48 2017-07-24] Checking default for jobs
[info] [19:56:48 2017-07-24] Sleeping for 5
[info] [19:56:53 2017-07-24] Checking default for jobs
[info] [19:56:53 2017-07-24] Sleeping for 5
[info] [19:56:58 2017-07-24] Checking default for jobs
[info] [19:56:58 2017-07-24] Sleeping for 5
[info] [19:57:03 2017-07-24] Checking default for jobs
[info] [19:57:03 2017-07-24] Found job on default

[notice] [19:57:03 2017-07-24] Starting work on (Job{default} | ID: 97ab28042n9ad4d900c459421eb06b
...
[info] [19:57:03 2017-07-24] Forked 25216 at 2017-07-24 19:57:03
.............
[info] [19:57:03 2017-07-24] Processing default since 2017-07-24 19:57:03
[notice] [19:57:07 2017-07-24] (Job{default} | ID: 97ab28042a369ad4d900c459421eb06b 
..... has finished
```
And after the first Job is finished, the worker is not showing the Polling message ( ie, checking default for jobs and sleeping for 5 ), and no messages are logged on the screen. 

ENV
====
PHP 7.1.7-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul  7 2017 09:41:45) ( NTS )
Symfony version : v2.8.17
Redis server v=3.2.9

How to figure out why are the workers getting stalled ?

Thanks !

**Comment by PhilETaylor** [comment] 2019-11-17 21:16
I have been unable to replicate this. As you are running Symfony 2.8.17 it might be time to close this unless its still happening in a modern version,.

**Closed as completed by PhilETaylor** 2019-11-17 21:16 UTC

**Comment by cfftony** [comment] 2022-08-10 11:02
I have the same issue, and it is caused by the grpc extension, remove it then it‘s work fine, Hope it helps you.
